spring:
  application:
    name: employee-service
server:
  port: ${PORT:8080}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl: 
     defaultZone: https://eureka-server-gcp.appspot.com/eureka
  instance:
    hostname: eureka-server-gcp.appspot.com
management:
  info:
    env:
      enabled: true